-- ============================================================
--  DSC Incident Tracker — MySQL Schema (with Auth)
-- ============================================================

CREATE DATABASE IF NOT EXISTS dsc_incidents
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dsc_incidents;

-- ── Lookup Tables ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS customers (
  id   TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE
);

INSERT IGNORE INTO customers (name) VALUES
  ('DSC - Emudhra'), ('DSC - Verasys'),
  ('DSC-Pantasign'), ('DSC - Speed Sign');

CREATE TABLE IF NOT EXISTS categories (
  id   TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

INSERT IGNORE INTO categories (name) VALUES
  ('Breakfix'), ('Devlopment Team'), ('Integration');

CREATE TABLE IF NOT EXISTS resources (
  id   TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL UNIQUE
);

INSERT IGNORE INTO resources (name) VALUES
  ('Senthil'), ('Aravinth'), ('Bharath'), ('Sugumaran'),
  ('Kanishka'), ('Benjamin'), ('Rubala'), ('Rajabharath');

-- ── Users Table ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id           INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
  username     VARCHAR(60)     NOT NULL UNIQUE,
  password_hash VARCHAR(255)   NOT NULL,
  full_name    VARCHAR(100)    NOT NULL,
  email        VARCHAR(120)    DEFAULT NULL,
  role         ENUM('admin','user') NOT NULL DEFAULT 'user',
  is_active    TINYINT(1)      NOT NULL DEFAULT 1,
  last_login   DATETIME        DEFAULT NULL,
  created_at   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Default admin: admin / Admin@123
-- Default user:  viewer / Viewer@123
-- (Passwords are bcrypt hashed — generated by app.py on first run)
-- Run: python app.py --create-users  to seed these accounts

-- ── Incidents Table ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS incidents (
  id               INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
  customer_id      TINYINT UNSIGNED NOT NULL,
  incident_ref     VARCHAR(50)     DEFAULT NULL,
  ca               VARCHAR(80)     DEFAULT NULL,
  category_id      TINYINT UNSIGNED NOT NULL,
  incident_date    DATE            NOT NULL,
  issue_reported   TEXT            NOT NULL,
  action_taken     TEXT            DEFAULT NULL,
  resource_id      TINYINT UNSIGNED NOT NULL,
  status           ENUM('Closed','Pending','Open') NOT NULL DEFAULT 'Open',
  days_taken       VARCHAR(60)     DEFAULT NULL,
  hours_spent      VARCHAR(30)     DEFAULT NULL,
  device_model     VARCHAR(40)     DEFAULT NULL,
  firmware_version VARCHAR(20)     DEFAULT NULL,
  remarks          TEXT            DEFAULT NULL,
  created_by       INT UNSIGNED    DEFAULT NULL,
  created_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_resource FOREIGN KEY (resource_id) REFERENCES resources(id),

  INDEX idx_status        (status),
  INDEX idx_incident_date (incident_date),
  INDEX idx_category      (category_id),
  INDEX idx_resource      (resource_id),
  INDEX idx_customer      (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── View ───────────────────────────────────────────────────

CREATE OR REPLACE VIEW v_incidents AS
SELECT
  i.id,
  c.name              AS customer,
  i.incident_ref,
  i.ca,
  cat.name            AS category,
  i.incident_date,
  i.issue_reported,
  i.action_taken,
  r.name              AS resource,
  i.status,
  i.days_taken,
  i.hours_spent,
  i.device_model,
  i.firmware_version,
  i.remarks,
  i.created_at,
  i.updated_at
FROM incidents  i
JOIN customers  c   ON c.id   = i.customer_id
JOIN categories cat ON cat.id = i.category_id
JOIN resources  r   ON r.id   = i.resource_id;
